name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Test run
        run: node Kha/make.js -t krom -g opengl --kha Kha --from test/Empty
